### ISSUE TITLE
Add Child Event Listeners

### ISSUE THREAD

**Issue by zabawaba99** [zabawaba99/firego#36]
Some snippets of what it looks like on different Firebase SDK

**Javascript**

``` javascript
// Get a reference to our posts
var ref = new Firebase("https://docs-examples.firebaseio.com/web/saving-data/fireblog/posts");

// Retrieve new posts as they are added to our database
ref.on("child_added", function(snapshot, prevChildKey) {
  var newPost = snapshot.val();
  console.log("Author: " + newPost.author);
  console.log("Title: " + newPost.title);
  console.log("Previous Post ID: " + prevChildKey);
});
```

**ios**

``` objective-c
// Get a reference to our posts
Firebase *ref = [[Firebase alloc] initWithUrl: @"https://docs-examples.firebaseio.com/web/saving-data/fireblog/posts"];

// Retrieve new posts as they are added to the database
[ref observeEventType:FEventTypeChildAdded withBlock:^(FDataSnapshot *snapshot) {
  NSLog(@"%@", snapshot.value[@"author"]);
  NSLog(@"%@", snapshot.value[@"title"]);
}];
```

**android**

``` java
// Get a reference to our posts
Firebase ref = new Firebase("https://docs-examples.firebaseio.com/web/saving-data/fireblog/posts");

ref.addChildEventListener(new ChildEventListener() {
    // Retrieve new posts as they are added to the database
    @Override
    public void onChildAdded(DataSnapshot snapshot, String previousChildKey) {
        BlogPost newPost = snapshot.getValue(BlogPost.class);
        System.out.println("Author: " + newPost.getAuthor());
        System.out.println("Title: " + newPost.getTitle());
    }

    //... ChildEventListener also defines onChildChanged, onChildRemoved,
    //    onChildMoved and onCanceled, covered in later sections.
});
```

---

The go interface will use callbacks similarly to how the other firebase sdks.

Methods to be added:
- `ChildAdded`
- `ChildChanged`
- `ChildRemoved`
- `ChildMoved`

**Comment by zabawaba99** [comment]
Some previous conversation was had on https://github.com/zabawaba99/firego/issues/17#issuecomment-191241529

**Comment by zabawaba99** [comment]
@raulsntos I started some work on this in a new branch called `event-funcs`. I've only added the `ChildAdded` events so far but if you'd like to give it a shot so far I'd love some feedback.

**Comment by raulsntos** [comment]
I'm a bit busy at the time, but I'll see if I can give it a try next week

**Comment by raulsntos** [comment]
I've tested it and so far it's great, what are you planning to do with DataSnapshot? Will you be adding val() and key() like in [Javascript](https://www.firebase.com/docs/web/api/datasnapshot/)? I think it would be nice to have those functions there, since right now you only get the JSON and without the ID you can't modify or delete the received data (at least I can't think of a way to do that, with Watch I save the event.Path when it comes while listening and if the items were already in firebase I just use range event.Data.(map[string]interface{}) in order to get all the IDs, like you recommended in #17).

Also, should val() and key() be functions or public fields of the DataSnapshot struct? I think the latter is the go way but I'm not really an expert here.

**Comment by zabawaba99** [comment]
Glad to hear that it's work as expected @raulsntos !. I did want to expand the DataSnapshot a bit more. I think adding the `Value` and `Key` as fields would be a good addition as well as perhaps adding in some functions to navigate through child fields
