### ISSUE TITLE
StopWatching() -> panic: send on closed channel

### ISSUE THREAD

**Issue by jlgale** [zabawaba99/firego#66]
Seen on 7c8d46a1fca7ae5cebcb2cf98fd10966dae20dab after calling `Firebase.StopWatching()`

```
panic: send on closed channel

goroutine 124 [running]:
panic(0x53ece0, 0xc420a5a9b0)
  /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
.../vendor/github.com/zabawaba99/firego.(*Firebase).Watch.func1(0xc4200e8fc0, 0xc420a5a309, 0xc4200e9020)
  /.../vendor/github.com/zabawaba99/firego/watch.go:99 +0x70
created by sigma/vendor/github.com/zabawaba99/firego.(*Firebase).Watch
  /.../vendor/github.com/zabawaba99/firego/watch.go:100 +0x132
```

**Comment by jlgale** [comment]
I didn't follow the code too closely, but I wonder why this channel is being closed at all? https://github.com/zabawaba99/firego/blob/master/watch.go#L105

**Comment by zabawaba99** [comment]
@jgeiger Thanks for reporting the issue. You raise a great point about not having to close the channel since no one is listening for the close. Let me see if I can reproduce the panic through a test and I'll push a quick fix

**Comment by zabawaba99** [comment]
I was able to reproduce it in a test so we don't come across this issue again. Will be pushing a fix shortly

**Comment by jlgale** [comment]
Thanks for the quick fix. One thing though:
```
	stop := make(chan struct{})
	events, err := fb.watch(stop)
	if err != nil {
		return err
	}

	var closedManually bool

	go func() {
		<-fb.stopWatching
		closedManually = true
		stop <- struct{}{}
	}()
```
I wonder if you should be allocating the `stop` channel like this: `make(chan struct{}, 1)`. If you leave the channel unbuffered, the `stop <- struct{}{}`  operation can block forever, leaking a goroutine.

**Comment by zabawaba99** [comment]
Hrmm, that's a good point. I'm going to play around with this a little bit to see if there are some leaking go routines. However, at first glance it looks like it should be ok since by [the time the unexported watch function exits](https://github.com/zabawaba99/firego/blob/master/watch.go#L89) there is a [routine waiting on the `stop` channel](https://github.com/zabawaba99/firego/blob/master/watch.go#L162).

In any case, writing some tests to validate the count of go routines would be a good idea.
