### ISSUE TITLE
Firebase Transaction Function Request

### ISSUE THREAD

**Issue by tqwewe** [zabawaba99/firego#81]
Firebase has a function **`transaction(transactionUpdate, onComplete, applyLocally)`** which you can view **[here](https://firebase.google.com/docs/reference/js/firebase.database.Reference#transaction)**.

The function's purpose is explained **[here](https://firebase.google.com/docs/database/web/read-and-write#save_data_as_transactions)**:
> When working with data that could be corrupted by concurrent modifications, such as incremental counters, you can use a transaction operation.

This is extremely useful and would be a great feature to firego as it is currently unsupported as far as I believe.

Any thoughts?

**Comment by zabawaba99** [comment]
I think having a transaction would be a great idea. However, it looks like there is no exposed way of doing this through their rest API. I'm not too sure that we would be able to do this unless we inject data into someone's database. If we did add data to someone's database then we could implement transactions but they would only work when another firego client accesses data.

**Comment by tqwewe** [comment]
It's a shame. Maybe I'll look into it to see if it's possible without injecting data like that.
Something like looking at the source code of the javascript transaction() function could help.

**Comment by zabawaba99** [comment]
That would be awesome @Acidic9 , let me know what you find!

**Comment by a13xb** [comment]
Their official SDKs are open-source now, so it should be easier to find out how it works now.

**Comment by rockwotj** [comment]
The Realtime Database just added support for conditional requests (AKA transactions) via the REST API. Instead of trying to re-create the wire protocol for golang, I think it's better to use the REST API.

See the docs here: https://firebase.google.com/docs/reference/rest/database/#section-conditional-requests

/cc @caseycrogers

**Comment by zabawaba99** [comment]
Good catch @rockwotj. How would we make something like this work? What sort of API makes sense for this library? Looking at the [firebase-admin-java](https://github.com/firebase/firebase-admin-java) as a reference, it seems like they're using the internal snapshot of the data to perform the transaction before sending it off to the server. We could do something similar with:

```go
type TransactionFn func(map[string]interface{}) error

func (f *Firebase) inTransaction(fn TransactionFn) error {
	// fetch etag
	// execute transaction
	// if no error, commit
}
```

Not too sure about the `map[string]interface{}` - we could probably have another `type` that makes it easier for a user to `put` things into it.

**Comment by rockwotj** [comment]
Are you planning on doing retries similar to the SDKs? They currently implement sudo-code like this:

```python
success = false
while not success
  value, etag = ref.read_from_database()
  new_value = compute_new_value_in_trasaction(value)
  response = ref.set_new_value_with_etag(new_value, etag)
  if response.status_code == 200
    success = true
```

This is essentially a [compare and swap operation](https://golang.org/pkg/sync/atomic/#CompareAndSwapUint64), and the SDKs do this transparently. I think firego can do the same, but I don't think we can assume a map, and we need to give access to the current value and allow them to return a new value to be saved. Maybe something like:

```golang
// Input of the current data at the location, and return the new data that needs to be set at 
// that location, or an error to abort the transaction.
type TransactionFn func(interface{}) interface{}, error
```

This way people can atomically increment a counter or something of the like (which is why if it's just a number we can't use a map). Thoughts?

**Comment by zabawaba99** [comment]
I don't see any harm in performing retries and keeping with the same criteria that the official SDKs do. Also, I completely overlooked the return of the transaction handler - good catch. Proposal looks solid. Going to see if I give this a whirl in the next couple of days (unless someone beats me to it and opens up a PR before me). 

Thanks for the feedback!

**Comment by zabawaba99** [comment]
I created #86 with an initial implementation of transactions. Going to write some tests to ensure everything works as expected before merging.
